-- src/test/resources/schema.sql

DROP TABLE transaction_history CASCADE;
DROP TABLE account CASCADE;
DROP TABLE member CASCADE;
DROP SEQUENCE account_seq;
DROP SEQUENCE history_seq;

-- 1. Member(회원) 테이블 생성
CREATE TABLE member (
                        member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR2(100) NOT NULL UNIQUE,
                        password VARCHAR2(255) NOT NULL,
                        name VARCHAR2(100) NOT NULL,
                        role VARCHAR2(50) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Account(계좌) 테이블 PK 생성을 위한 시퀀스
CREATE SEQUENCE account_seq START WITH 100000 INCREMENT BY 1;

-- 3. Account(계좌) 테이블 생성
CREATE TABLE account (
                         account_id NUMBER PRIMARY KEY,
                         username VARCHAR2(100) NOT NULL,
                         balance NUMBER DEFAULT 0 NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_account_member FOREIGN KEY (username) REFERENCES member(username) ON DELETE CASCADE
);

-- 4. Transaction_History(거래 내역) 테이블 PK 생성을 위한 시퀀스
CREATE SEQUENCE history_seq START WITH 1 INCREMENT BY 1;

-- 5. Transaction_History(거래 내역) 테이블 생성
CREATE TABLE transaction_history (
                                     history_id NUMBER PRIMARY KEY,
                                     from_account_id NUMBER NOT NULL,
                                     to_account_id NUMBER NOT NULL,
                                     amount NUMBER NOT NULL,
                                     status VARCHAR2(50) NOT NULL,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);