-- src/test/resources/schema.sql

-- 1. Account(계좌) 테이블 PK 생성을 위한 시퀀스
CREATE SEQUENCE IF NOT EXISTS account_seq START WITH 100000 INCREMENT BY 1;

-- 2. Member(회원) 테이블 생성
CREATE TABLE member (
                        member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 문법 수정
                        username VARCHAR(50) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        name VARCHAR(50) NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Account(계좌) 테이블 생성
CREATE TABLE account (
                         account_id BIGINT PRIMARY KEY,
                         username VARCHAR(50) NOT NULL,
                         balance BIGINT DEFAULT 0 NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Transaction_History(거래 내역) 테이블 PK 생성을 위한 시퀀스
CREATE SEQUENCE IF NOT EXISTS history_seq START WITH 1 INCREMENT BY 1;

-- 5. Transaction_History(거래 내역) 테이블 생성
CREATE TABLE transaction_history (
                                     history_id BIGINT PRIMARY KEY,
                                     from_account_id BIGINT NOT NULL,
                                     to_account_id BIGINT NOT NULL,
                                     amount BIGINT NOT NULL,
                                     status VARCHAR(20) NOT NULL,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);